# Default values for aps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

activiti-app:
  reviewWorkflows:
    enabled: true
  image:  
    repository: alfresco/process-services
    tag: 1.9.0.1
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    hosts:       
    - aps.127.0.0.1.nip.io
    annotations:
      kubernetes.io/ingress.class: nginx

postgresql:
  enabled: true
  name: postgres
  pullPolicy: IfNotPresent
  existingSecret: "aps-postgresql"
  persistence:
    enabled: true
