apiVersion: v1
kind: Secret
metadata:
  name: aps-postgresql
  labels:
    app: {{ include "aps.name" . }}
    chart: {{ include "aps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
{{- if .Values.postgresPassword }}
  postgres-password:  {{ .Values.postgresPassword | b64enc | quote }}
{{- else }}
  postgres-password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
