apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "aps.fullname" . }}
  labels:
    app: {{ include "aps.name" . }}
    chart: {{ include "aps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "aps.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "aps.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
      - name: license-volume
        secret:
          secretName: activiti.lic
    {{- if .Values.initEnv.WAIT_HOSTS }}
      initContainers:
        - name: init-container
          image: introproventures/emailbpm-docker-wait-for-it:0.0.1
          command: ['/usr/local/bin/bash', '-c', '/wait-for-it.sh {{ tpl .Values.initEnv.WAIT_HOSTS . }}']
          imagePullPolicy: {{ .Values.image.pullPolicy }}
   {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: license-volume
            mountPath: "/root/.activiti/enterprise-license/"
            readOnly: true
          env:
          - name: DATASOURCE_USERNAME
            value: {{ .Values.postgresql.name }}
          - name: DATASOURCE_DRIVER
            value: org.postgresql.Driver 
          - name: DATASOURCE_URL
            value: jdbc:postgresql://{{ .Release.Name }}-{{ .Values.postgresql.host }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.name }}
          - name: DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "aps-postgresql"
                key: postgres-password
          - name: HIBERNATE_DIALECT
            value: org.hibernate.dialect.PostgreSQL82Dialect
          - name: APP_REVIEW_WORKFLOWS_ENABLED
            value: {{ .Values.reviewWorkflows.enabled | quote }}
          {{- if .Values.extraEnv }}
{{ toYaml .Values.extraEnv | indent 10 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
