apiVersion: v1
kind: Service
metadata:
  name: {{ include "aps.fullname" . }}
  labels:
    app: {{ include "aps.name" . }}
    chart: {{ include "aps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}    
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "aps.name" . }}
    release: {{ .Release.Name }}
